# Generated by Django 2.2.1 on 2021-12-15 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=6, verbose_name='レストランID')),
                ('wine_id', models.CharField(max_length=6, verbose_name='ワインID')),
                ('num', models.IntegerField(verbose_name='本数')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
            ],
            options={
                'verbose_name': 'カート情報',
                'verbose_name_plural': 'カート情報',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=6, verbose_name='レストランID')),
                ('wine_id', models.CharField(max_length=6, verbose_name='ワインID')),
                ('num', models.IntegerField(verbose_name='本数')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
            ],
            options={
                'verbose_name': '発注履歴情報',
                'verbose_name_plural': '発注履歴情報',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.IntegerField(choices=[(0, '男性'), (1, '女性')], verbose_name='性別')),
                ('household_num', models.IntegerField(verbose_name='世帯人数')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー情報データ',
                'verbose_name_plural': 'ユーザー情報データ',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='ワイン名')),
                ('kind', models.CharField(max_length=20, verbose_name='タイプ')),
                ('origin', models.CharField(max_length=30, verbose_name='産地')),
                ('type', models.CharField(max_length=30, verbose_name='品種')),
                ('year', models.IntegerField(verbose_name='収穫年')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='在庫')),
            ],
            options={
                'verbose_name': 'ワインの情報',
                'verbose_name_plural': 'ワイン情報',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='レストラン名')),
                ('pref_name', models.CharField(max_length=20, verbose_name='都道府県')),
                ('city_name', models.CharField(max_length=50, verbose_name='市区')),
                ('district_name', models.CharField(max_length=50, verbose_name='町村')),
                ('phone_number', models.CharField(max_length=18, verbose_name='電話番号')),
                ('appearance', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='店舗写真')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー情報データ',
                'verbose_name_plural': 'ユーザー情報データ',
            },
        ),
        migrations.CreateModel(
            name='RentRoom',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='物件ID')),
                ('pref_name', models.CharField(max_length=20, verbose_name='都道府県')),
                ('city_name', models.CharField(max_length=50, verbose_name='市区町村')),
                ('district_name', models.CharField(max_length=50, verbose_name='町丁目')),
                ('built_year', models.IntegerField(verbose_name='築年')),
                ('structure', models.CharField(max_length=20, verbose_name='構造')),
                ('top_floor_num', models.IntegerField(verbose_name='最上階数')),
                ('room_type', models.CharField(max_length=20, verbose_name='間取り')),
                ('price', models.FloatField(verbose_name='平米単価')),
                ('area', models.FloatField(verbose_name='専有面積')),
                ('latitude', models.FloatField(verbose_name='物件緯度')),
                ('longitude', models.FloatField(verbose_name='物件経度')),
                ('nearest_station', models.CharField(max_length=50, verbose_name='最寄り駅')),
                ('dist_to_nearest_station', models.FloatField(verbose_name='最寄駅までの距離')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='winedelivery.Profile', verbose_name='所有者')),
            ],
            options={
                'verbose_name': '賃貸物件データ',
                'verbose_name_plural': '賃貸物件データ',
            },
        ),
    ]
