# Generated by Django 2.2.1 on 2021-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winedelivery', '0002_auto_20211221_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
