# Generated by Django 2.2.1 on 2021-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winedelivery', '0003_auto_20211221_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
